### ISSUE TITLE
#include <pthread.h> needed on Mac OS X

### ISSUE THREAD

**Issue by Congee** [2ed/xmplay#4]
Header `pthread.h` is required. I've tried both clang and gcc-6.
To suppress the compiler warning, you'd better `#include <unistd.h>`

BTW, the code works like a charm and simple. Thanks for your work. :)

**Comment by 2ed** [comment]
Thanks for the feedback! You can open a pull request, I'm not really able to test it on Mac OS.
Anyway, all the credit goes to @taptap since he helped me out with the C+lua magic part.
